# Generated by Django 3.0.8 on 2020-08-07 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0003_auto_20200807_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(125), django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator('Invalid Email')]),
        ),
    ]
