# Generated by Django 3.0.8 on 2020-08-07 06:16

import django.core.validators
from django.db import migrations, models
import modelapp.validators
import re


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0004_auto_20200807_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(125), django.core.validators.MinValueValidator(2), modelapp.validators.validate_even_number]),
        ),
    ]
