# Generated by Django 3.0.8 on 2020-08-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
