# Generated by Django 3.0.8 on 2020-08-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('article_published', models.CharField(max_length=256)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationshipapp.Article')),
            ],
        ),
    ]
