# Generated by Django 3.0.8 on 2020-08-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationshipapp', '0003_auto_20200808_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='article_published',
        ),
    ]
